/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simo;

import javax.swing.JFrame;
import javax.swing.JLabel;

import base.Protocol;
import graph.GraphType;
import multiSkipGraph.MsController;

/**
 *
 * @author Linghui Luo
 */
public class MultiModeFrame extends javax.swing.JDialog {

	/**
	 *
	 */
	private static final long serialVersionUID = -3638961347622336709L;
	java.awt.Frame parent;

	/**
	 * Creates new form MultiModeFrame
	 */
	public MultiModeFrame(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		this.parent = parent;
		this.initComponents();
	}

	private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		System.exit(0);
	}//GEN-LAST:event_formWindowClosing

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel_graphSize = new javax.swing.JLabel();
		jLabel_search = new javax.swing.JLabel();
		jRadioButton_scaleFree = new javax.swing.JRadioButton();
		jRadioButton_random = new javax.swing.JRadioButton();
		jLabel_graphType = new javax.swing.JLabel();
		jButton_simulate = new javax.swing.JButton();
		jButton_cancel = new javax.swing.JButton();
		jLabel_min = new javax.swing.JLabel();
		jLabel_max = new javax.swing.JLabel();
		jLabel_step = new javax.swing.JLabel();
		jTextField_min = new javax.swing.JTextField();
		jTextField_step = new javax.swing.JTextField();
		jTextField_max = new javax.swing.JTextField();
		jRadioButton_absolute = new javax.swing.JRadioButton();
		jRadioButton_relative = new javax.swing.JRadioButton();
		jTextField_absolute = new javax.swing.JTextField();
		jTextField_relative = new javax.swing.JTextField();
		jLabel_times = new javax.swing.JLabel();
		jLabel_test = new javax.swing.JLabel();
		jTextField_test = new javax.swing.JTextField();
		jRadioButton_randomAvgDegree = new javax.swing.JRadioButton();
		jTextField_degree = new javax.swing.JTextField();
		jTextField_avgDegree = new javax.swing.JTextField();
		jLabel_graphType1 = new javax.swing.JLabel();
		jRadioButton_naive = new javax.swing.JRadioButton();
		jRadioButton_alternative = new javax.swing.JRadioButton();
		jRadioButton_both = new javax.swing.JRadioButton();
		jRadioButton_batch = new javax.swing.JRadioButton();
		jTextField_batch = new javax.swing.JTextField();
		jLabel_batch = new javax.swing.JLabel();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		this.addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent evt) {
				MultiModeFrame.this.formWindowClosing(evt);
			}
		});

		jLabel_graphSize.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_graphSize.setText("Graph size:");

		jLabel_search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_search.setText("Number of search messages:");

		jRadioButton_scaleFree.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_scaleFree.setText("Scale-free graph");
		jRadioButton_scaleFree.setSelected(true);
		jRadioButton_scaleFree.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jRadioButton_scaleFreeActionPerformed(evt);
			}
		});

		jRadioButton_random.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_random.setText("Random graph");
		jRadioButton_random.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jRadioButton_randomActionPerformed(evt);
			}
		});

		jLabel_graphType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_graphType.setText("Graph type:");

		jButton_simulate.setBackground(java.awt.SystemColor.activeCaption);
		jButton_simulate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jButton_simulate.setText("Simulate");
		jButton_simulate.setMaximumSize(new java.awt.Dimension(70, 20));
		jButton_simulate.setMinimumSize(new java.awt.Dimension(70, 20));
		jButton_simulate.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jButton_simulateActionPerformed(evt);
			}
		});

		jButton_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jButton_cancel.setText("Cancel");
		jButton_cancel.setMaximumSize(new java.awt.Dimension(70, 20));
		jButton_cancel.setMinimumSize(new java.awt.Dimension(70, 20));
		jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jButton_cancelActionPerformed(evt);
			}
		});

		jLabel_min.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_min.setText("Minimum:");

		jLabel_max.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_max.setText("Maximum:");

		jLabel_step.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_step.setText("Step value:");

		jTextField_min.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_min.setText("10");
		jTextField_min.setPreferredSize(new java.awt.Dimension(50, 21));

		jTextField_step.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_step.setText("50");
		jTextField_step.setPreferredSize(new java.awt.Dimension(50, 21));

		jTextField_max.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_max.setText("1000");
		jTextField_max.setPreferredSize(new java.awt.Dimension(50, 21));

		jRadioButton_absolute.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		//jRadioButton_absolute.setSelected(true);
		jRadioButton_absolute.setText("Absolute value");
		jRadioButton_absolute.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jRadioButton_absoluteActionPerformed(evt);
			}
		});

		jRadioButton_relative.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_relative.setText("Relative to graph size ");
		jRadioButton_relative.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jRadioButton_relativeActionPerformed(evt);
			}
		});

		jTextField_absolute.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_absolute.setText("0");
		jTextField_absolute.setPreferredSize(new java.awt.Dimension(50, 21));

		jTextField_relative.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_relative.setText("2");
		jTextField_relative.setPreferredSize(new java.awt.Dimension(50, 21));

		jLabel_times.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_times.setText("times graph size");

		jLabel_test.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_test.setText("Number of tests per graph size:");

		jTextField_test.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_test.setText("2");
		jTextField_test.setPreferredSize(new java.awt.Dimension(50, 21));

		jRadioButton_randomAvgDegree.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_randomAvgDegree.setText("Random graph with avg. degree");
		jRadioButton_randomAvgDegree.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jRadioButton_randomAvgDegreeActionPerformed(evt);
			}
		});

		jTextField_degree.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_degree.setText("2");
		jTextField_degree.setPreferredSize(new java.awt.Dimension(50, 21));

		jTextField_avgDegree.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_avgDegree.setText("4");
		jTextField_avgDegree.setPreferredSize(new java.awt.Dimension(50, 21));

		jLabel_graphType1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_graphType1.setText("Protocol type:");

		jRadioButton_naive.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jRadioButton_naive.setText("MultiSkipGraph protocol");
		jRadioButton_naive.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jRadioButton_naiveActionPerformed(evt);
			}
		});

		jRadioButton_alternative.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jRadioButton_alternative.setText("MultiSkipGraph* protocol");
		jRadioButton_alternative.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jRadioButton_alternativeActionPerformed(evt);
			}
		});

		jRadioButton_both.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_both.setText("Both for comparision");
		jRadioButton_both.setSelected(true);
		jRadioButton_both.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jRadioButton_bothActionPerformed(evt);
			}
		});

		jRadioButton_batch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_batch.setText("Send batches till stable");
		jRadioButton_batch.setSelected(true);
		jRadioButton_batch.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MultiModeFrame.this.jRadioButton_batchActionPerformed(evt);
			}
		});

		jTextField_batch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_batch.setText("10");
		jTextField_batch.setPreferredSize(new java.awt.Dimension(50, 21));

		jLabel_batch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_batch.setText("searches per batch");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
		this.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(36, 36, 36).addGroup(layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel_search).addContainerGap())
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel_graphSize)
												.addComponent(jRadioButton_absolute).addComponent(jRadioButton_relative)
												.addGroup(layout.createSequentialGroup().addComponent(jLabel_min)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jTextField_min, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(18, 18, 18).addComponent(jLabel_step)))
										.addGap(28, 28, 28)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(jTextField_step, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
														.addComponent(jLabel_max)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jTextField_max,
																javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addContainerGap(49, Short.MAX_VALUE))
												.addGroup(layout.createSequentialGroup().addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addComponent(jTextField_batch, javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jLabel_batch))
														.addComponent(jTextField_absolute, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(layout.createSequentialGroup()
																.addComponent(jTextField_relative, javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(jLabel_times)))
														.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jRadioButton_batch)
												.addComponent(jLabel_graphType)
												.addGroup(layout.createSequentialGroup()
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jRadioButton_randomAvgDegree).addComponent(jRadioButton_scaleFree)
																.addComponent(jRadioButton_random).addComponent(jLabel_graphType1)
																.addComponent(jRadioButton_naive).addComponent(jRadioButton_alternative)
																.addComponent(jRadioButton_both)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(jButton_simulate, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jLabel_test)))
														.addGap(10, 10, 10)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField_test, javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jTextField_degree, javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jTextField_avgDegree, javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
																		javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(0, 144, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(45, 45, 45).addComponent(jLabel_graphSize)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel_min)
								.addComponent(jLabel_max).addComponent(jLabel_step)
								.addComponent(jTextField_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_step, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel_search).addGap(20, 20, 20)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jRadioButton_absolute)
								.addComponent(jTextField_absolute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(10, 10, 10)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jRadioButton_relative)
								.addComponent(jTextField_relative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel_times, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(10, 10, 10)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jRadioButton_batch)
								.addComponent(jTextField_batch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE).addComponent(jLabel_graphType)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jRadioButton_scaleFree)
								.addComponent(jTextField_degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField_avgDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jRadioButton_randomAvgDegree))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jRadioButton_random).addGap(20, 20, 20)
						.addComponent(jLabel_graphType1).addGap(18, 18, 18).addComponent(jRadioButton_naive)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jRadioButton_alternative)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jRadioButton_both).addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel_test).addComponent(
								jTextField_test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(28, 28, 28)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton_simulate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(35, 35, 35)));

		this.pack();
		this.setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jRadioButton_scaleFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_scaleFreeActionPerformed
		if (this.jRadioButton_scaleFree.isSelected()) {
			this.jTextField_degree.setEnabled(true);
			this.jTextField_avgDegree.setEnabled(false);
			this.jRadioButton_randomAvgDegree.setSelected(false);
			this.jRadioButton_random.setSelected(false);
		} else {
			this.jTextField_degree.setEnabled(false);
			this.jTextField_avgDegree.setEnabled(true);
			this.jRadioButton_randomAvgDegree.setSelected(true);
			this.jRadioButton_random.setSelected(false);
		}
	}//GEN-LAST:event_jRadioButton_scaleFreeActionPerformed

	private void jRadioButton_randomAvgDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_randomAvgDegreeActionPerformed
		if (this.jRadioButton_randomAvgDegree.isSelected()) {
			this.jTextField_avgDegree.setEnabled(true);
			this.jTextField_degree.setEnabled(false);
			this.jRadioButton_random.setSelected(false);
			this.jRadioButton_scaleFree.setSelected(false);
		} else {
			this.jTextField_avgDegree.setEnabled(false);
			this.jTextField_degree.setEnabled(false);
			this.jRadioButton_random.setSelected(true);
			this.jRadioButton_scaleFree.setSelected(false);
		}
	}//GEN-LAST:event_jRadioButton_randomAvgDegreeActionPerformed

	private void jRadioButton_randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_randomActionPerformed
		if (this.jRadioButton_random.isSelected()) {
			this.jTextField_avgDegree.setEnabled(false);
			this.jTextField_degree.setEnabled(false);
			this.jRadioButton_randomAvgDegree.setSelected(false);
			this.jRadioButton_scaleFree.setSelected(false);
		} else {
			this.jTextField_avgDegree.setEnabled(false);
			this.jTextField_degree.setEnabled(true);
			this.jRadioButton_scaleFree.setSelected(true);
			this.jRadioButton_randomAvgDegree.setSelected(false);
		}
	}//GEN-LAST:event_jRadioButton_randomActionPerformed

	private void jRadioButton_absoluteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_absoluteActionPerformed
		// TODO add your handling code here:
		if (this.jRadioButton_absolute.isSelected()) {
			this.jTextField_absolute.setEnabled(true);
			this.jRadioButton_relative.setSelected(false);
			this.jTextField_relative.setEnabled(false);
			this.jRadioButton_batch.setSelected(false);
			this.jTextField_batch.setEnabled(false);
		} else {
			this.jTextField_absolute.setEnabled(false);
			this.jRadioButton_relative.setSelected(true);
			this.jTextField_relative.setEnabled(true);
		}
	}//GEN-LAST:event_jRadioButton_absoluteActionPerformed

	private void jRadioButton_relativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_relativeActionPerformed
		// TODO add your handling code here:
		if (this.jRadioButton_relative.isSelected()) {
			this.jTextField_relative.setEnabled(true);
			this.jRadioButton_absolute.setSelected(false);
			this.jTextField_absolute.setEnabled(false);
			this.jRadioButton_batch.setSelected(false);
			this.jTextField_batch.setEnabled(false);
		} else {
			this.jTextField_relative.setEnabled(false);
			this.jRadioButton_batch.setSelected(true);
			this.jTextField_batch.setEnabled(true);
		}
	}//GEN-LAST:event_jRadioButton_relativeActionPerformed

	private void jRadioButton_batchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_batchActionPerformed
		if (this.jRadioButton_batch.isSelected()) {
			this.jTextField_batch.setEnabled(true);
			this.jRadioButton_absolute.setSelected(false);
			this.jTextField_absolute.setEnabled(false);
			this.jRadioButton_relative.setSelected(false);
			this.jTextField_relative.setEnabled(false);
		} else {
			this.jTextField_batch.setEnabled(false);
			this.jRadioButton_absolute.setSelected(true);
			this.jTextField_absolute.setEnabled(true);
		}
	}//GEN-LAST:event_jRadioButton_batchActionPerformed

	private void jRadioButton_naiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_naiveActionPerformed
		if (this.jRadioButton_naive.isSelected()) {
			this.jRadioButton_alternative.setSelected(false);
			this.jRadioButton_both.setSelected(false);
		} else {
			this.jRadioButton_alternative.setSelected(true);
			this.jRadioButton_both.setSelected(false);
		}
	}//GEN-LAST:event_jRadioButton_naiveActionPerformed

	private void jRadioButton_alternativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_alternativeActionPerformed
		if (this.jRadioButton_alternative.isSelected()) {
			this.jRadioButton_naive.setSelected(false);
			this.jRadioButton_both.setSelected(false);
		} else {
			this.jRadioButton_naive.setSelected(true);
			this.jRadioButton_both.setSelected(false);
		}
	}//GEN-LAST:event_jRadioButton_alternativeActionPerformed

	private void jRadioButton_bothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_bothActionPerformed
		if (this.jRadioButton_both.isSelected()) {
			this.jRadioButton_naive.setSelected(false);
			this.jRadioButton_alternative.setSelected(false);
		} else {
			this.jRadioButton_naive.setSelected(true);
			this.jRadioButton_alternative.setSelected(false);
		}
	}//GEN-LAST:event_jRadioButton_bothActionPerformed

	private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
		this.setVisible(false);
		if (this.parent != null) {
			this.parent.setVisible(true);
		}
		this.dispose();
	}//GEN-LAST:event_jButton_cancelActionPerformed

	private void jButton_simulateActionPerformed(java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_jButton_simulateActionPerformed
		this.setVisible(false);
		JFrame jframe = new JFrame("Running...");
		jframe.setSize(300, 100);
		jframe.setVisible(true);
		jframe.setDefaultCloseOperation(EXIT_ON_CLOSE);
		jframe.add(new JLabel("Close this window to terminate the program!"));
		jframe.setLocationRelativeTo(null);
		int minNodes = Integer.parseInt(this.jTextField_min.getText());
		int step = Integer.parseInt(this.jTextField_step.getText());
		int maxNodes = Integer.parseInt(this.jTextField_max.getText());
		int numOfTests = Integer.parseInt(this.jTextField_test.getText());
		int searches = 0;
		boolean absolute = true;
		boolean batch = false;
		int batchSize = 0;
		if (this.jRadioButton_absolute.isSelected()) {
			searches = Integer.parseInt(this.jTextField_absolute.getText());
		}
		if (this.jRadioButton_relative.isSelected()) {
			absolute = false;
			searches = Integer.parseInt(this.jTextField_relative.getText());
		}
		if (this.jRadioButton_batch.isSelected()) {
			batch = true;
			batchSize = Integer.parseInt(this.jTextField_batch.getText());
		}
		int degree = Integer.parseInt(this.jTextField_degree.getText());
		GraphType graphType = GraphType.ScaleFree;
		if (this.jRadioButton_randomAvgDegree.isSelected()) {
			degree = Integer.parseInt(this.jTextField_avgDegree.getText());
			graphType = GraphType.RandomAvgDegree;
		}
		if (this.jRadioButton_random.isSelected()) {
			graphType = GraphType.Random;
		}
		Protocol protocol = Protocol.Naive;
		if (this.jRadioButton_alternative.isSelected()) {
			protocol = Protocol.Alternative;
		}
		if (this.jRadioButton_both.isSelected()) {
			protocol = Protocol.Both;
		}
		MsController.getInstance().setProperties(protocol, minNodes, searches, graphType, degree, numOfTests, true, false);
		if (!batch) {
			MsController.getInstance().simulateMulti(protocol, minNodes, step, maxNodes, absolute, searches, MultiModeFrame.this);
		} else {
			MsController.getInstance().simulateMultiToStable(protocol, minNodes, step, maxNodes, batchSize, MultiModeFrame.this);
		}
	}//GEN-LAST:event_jButton_simulateActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MultiModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MultiModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MultiModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MultiModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				MultiModeFrame dialog = new MultiModeFrame(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton_cancel;
	private javax.swing.JButton jButton_simulate;
	private javax.swing.JLabel jLabel_batch;
	private javax.swing.JLabel jLabel_graphSize;
	private javax.swing.JLabel jLabel_graphType;
	private javax.swing.JLabel jLabel_graphType1;
	private javax.swing.JLabel jLabel_max;
	private javax.swing.JLabel jLabel_min;
	private javax.swing.JLabel jLabel_search;
	private javax.swing.JLabel jLabel_step;
	private javax.swing.JLabel jLabel_test;
	private javax.swing.JLabel jLabel_times;
	private javax.swing.JRadioButton jRadioButton_absolute;
	private javax.swing.JRadioButton jRadioButton_alternative;
	private javax.swing.JRadioButton jRadioButton_batch;
	private javax.swing.JRadioButton jRadioButton_both;
	private javax.swing.JRadioButton jRadioButton_naive;
	private javax.swing.JRadioButton jRadioButton_random;
	private javax.swing.JRadioButton jRadioButton_randomAvgDegree;
	private javax.swing.JRadioButton jRadioButton_relative;
	private javax.swing.JRadioButton jRadioButton_scaleFree;
	private javax.swing.JTextField jTextField_absolute;
	private javax.swing.JTextField jTextField_avgDegree;
	private javax.swing.JTextField jTextField_batch;
	private javax.swing.JTextField jTextField_degree;
	private javax.swing.JTextField jTextField_max;
	private javax.swing.JTextField jTextField_min;
	private javax.swing.JTextField jTextField_relative;
	private javax.swing.JTextField jTextField_step;
	private javax.swing.JTextField jTextField_test;
	// End of variables declaration//GEN-END:variables
}
