/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Simo;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Hashtable;

import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.graphstream.graph.Graph;
import org.graphstream.ui.j2dviewer.J2DGraphRenderer;
import org.graphstream.ui.swingViewer.View;
import org.graphstream.ui.swingViewer.Viewer;

/**
 *
 * @author Linghui Luo
 */
public class ShowGraphFrame extends javax.swing.JFrame {

	/**
	 *
	 */
	private static final long serialVersionUID = 18955730288187759L;

	private final JDialog parent;
	private View graphView;
	private final javax.swing.JPanel jPanel_graph = new JPanel();

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JSplitPane jSplitPane;

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form simoFrame
	 */
	public ShowGraphFrame(JDialog parent, int posMode) {
		this.parent = parent;
		this.initComponents(posMode);
	}

	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		// TODO add your handling code here:
		System.exit(0);
	}// GEN-LAST:event_formWindowClosing

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents(int posMode) {

		this.jSplitPane = new javax.swing.JSplitPane();

		final Hashtable<Integer, JLabel> labelTable = new Hashtable<Integer, JLabel>();

		Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

		int height = (int) (screenSize.getHeight() * 0.8);
		int width = (int) screenSize.getWidth();
		if (posMode == 0) {
			if (width > (int) (height * 1.4)) {
				width = (int) (height * 1.4);
			}
		} else {
			width = width / 2;
		}
		this.addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent evt) {
				ShowGraphFrame.this.formWindowClosing(evt);
			}
		});

		this.jSplitPane.setDividerLocation(0.8);
		this.jSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
		this.jSplitPane.setMinimumSize(new java.awt.Dimension(width, height));
		this.jSplitPane.setPreferredSize(new java.awt.Dimension(width, height));

		int controlsWidth = 760;
		int leftGap = (width - controlsWidth) / 2;
		if (leftGap < 0) {
			leftGap = 0;
		}

		final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
		this.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(this.jSplitPane,
				javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(this.jSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0, Short.MAX_VALUE)));

		this.pack();
		this.setPreferredSize(new Dimension(width, height));
		this.setMinimumSize(new Dimension(width, height));
		if (posMode == 0) {
			this.setLocationRelativeTo(null);
		} else {
			if (posMode == 1) {
				this.setLocation(0, (int) (height * 0.1));
			} else {
				this.setLocation(width, (int) (height * 0.1));
			}
			this.pack();
		}
	}// </editor-fold>//GEN-END:initComponents

	public void setGraph(Graph graph) {
		this.setTitle(graph.getId());
		if (this.graphView != null) {
			this.remove(this.graphView);
		}
		final Viewer viewer = new Viewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
		this.graphView = viewer.addView("Graph", new J2DGraphRenderer(), false);
		graph.setAttribute("layout.stabilization-limit", 0.90);
		this.jPanel_graph.setLayout(new BorderLayout());
		this.jPanel_graph.add(this.graphView, BorderLayout.CENTER);
		this.jSplitPane.setLeftComponent(this.jPanel_graph);
		this.jSplitPane.setDividerLocation(0.99999);
		this.jSplitPane.setEnabled(false);
		this.setVisible(true);
	}
}
