/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simo;

import base.Protocol;
import graph.GraphType;
import multiSkipGraph.MsController;

/**
 *
 * @author Linghui Luo
 */
public class SingleModeFrame extends javax.swing.JDialog {

	/**
	 *
	 */
	private static final long serialVersionUID = 3896890075066309350L;

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (final ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SingleModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final InstantiationException ex) {
			java.util.logging.Logger.getLogger(SingleModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SingleModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SingleModeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				final SingleModeFrame dialog = new SingleModeFrame(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	java.awt.Frame parent;

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton_cancel;
	private javax.swing.JButton jButton_generate;
	private javax.swing.JCheckBox jCheckBox_makeFilm;
	private javax.swing.JCheckBox jCheckBox_saveData;
	private javax.swing.JLabel jLabel_graphSize;
	private javax.swing.JLabel jLabel_graphTypej;
	private javax.swing.JLabel jLabel_options;
	private javax.swing.JLabel jLabel_protocol;
	private javax.swing.JLabel jLabel_search;
	private javax.swing.JLabel jLabel_tests;
	private javax.swing.JRadioButton jRadioButton_alternative;
	private javax.swing.JRadioButton jRadioButton_both;
	private javax.swing.JRadioButton jRadioButton_naive;
	private javax.swing.JRadioButton jRadioButton_random;
	private javax.swing.JRadioButton jRadioButton_randomAvgDegree;
	private javax.swing.JRadioButton jRadioButton_scaleFree;
	private javax.swing.JTextField jTextField_avgDegree;
	private javax.swing.JTextField jTextField_degree;
	private javax.swing.JTextField jTextField_numOfNodes;
	private javax.swing.JTextField jTextField_numOfSearches;
	private javax.swing.JTextField jTextField_numOfTests;

	// End of variables declaration//GEN-END:variables
	/**
	 * Creates new form singeModeFrame
	 */
	public SingleModeFrame(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		this.parent = parent;
		this.initComponents();
	}

	private void formWindowClosing(java.awt.event.WindowEvent evt) {
		// GEN-FIRST:event_formWindowClosing
		System.exit(0);
	}// GEN-LAST:event_formWindowClosing

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel_graphSize = new javax.swing.JLabel();
		jLabel_search = new javax.swing.JLabel();
		jTextField_numOfNodes = new javax.swing.JTextField();
		jTextField_numOfSearches = new javax.swing.JTextField();
		jRadioButton_scaleFree = new javax.swing.JRadioButton();
		jRadioButton_randomAvgDegree = new javax.swing.JRadioButton();
		jLabel_graphTypej = new javax.swing.JLabel();
		jButton_generate = new javax.swing.JButton();
		jLabel_options = new javax.swing.JLabel();
		jCheckBox_makeFilm = new javax.swing.JCheckBox();
		jCheckBox_saveData = new javax.swing.JCheckBox();
		jButton_cancel = new javax.swing.JButton();
		jTextField_degree = new javax.swing.JTextField();
		jLabel_protocol = new javax.swing.JLabel();
		jRadioButton_naive = new javax.swing.JRadioButton();
		jRadioButton_alternative = new javax.swing.JRadioButton();
		jTextField_avgDegree = new javax.swing.JTextField();
		jRadioButton_random = new javax.swing.JRadioButton();
		jRadioButton_both = new javax.swing.JRadioButton();
		jLabel_tests = new javax.swing.JLabel();
		jTextField_numOfTests = new javax.swing.JTextField();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		this.addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent evt) {
				SingleModeFrame.this.formWindowClosing(evt);
			}
		});

		jLabel_graphSize.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_graphSize.setText("Graph size (max. 16):");

		jLabel_search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_search.setText("Number of search messages:");

		jTextField_numOfNodes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_numOfNodes.setText("16");
		jTextField_numOfNodes.setPreferredSize(new java.awt.Dimension(50, 21));

		jTextField_numOfSearches.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_numOfSearches.setText("0");
		jTextField_numOfSearches.setPreferredSize(new java.awt.Dimension(50, 21));

		jRadioButton_scaleFree.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_scaleFree.setSelected(true);
		jRadioButton_scaleFree.setText("Scale-free graph");
		jRadioButton_scaleFree.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SingleModeFrame.this.jRadioButton_scaleFreeActionPerformed(evt);
			}
		});

		jRadioButton_randomAvgDegree.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_randomAvgDegree.setText("Random graph with avg. degree");
		jRadioButton_randomAvgDegree.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SingleModeFrame.this.jRadioButton_randomAvgDegreeActionPerformed(evt);
			}
		});

		jLabel_graphTypej.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_graphTypej.setText("Graph type:");

		jButton_generate.setBackground(java.awt.SystemColor.activeCaption);
		jButton_generate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jButton_generate.setText("Simulate");
		jButton_generate.setMaximumSize(new java.awt.Dimension(70, 20));
		jButton_generate.setMinimumSize(new java.awt.Dimension(70, 20));
		jButton_generate.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SingleModeFrame.this.jButton_simulateActionPerformed(evt);
			}
		});

		jLabel_options.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_options.setText("Other options:");

		jCheckBox_makeFilm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jCheckBox_makeFilm.setText("Make a film");

		jCheckBox_saveData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jCheckBox_saveData.setSelected(false);
		jCheckBox_saveData.setText("Save measured data");

		jButton_cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jButton_cancel.setText("Cancel");
		jButton_cancel.setMaximumSize(new java.awt.Dimension(70, 20));
		jButton_cancel.setMinimumSize(new java.awt.Dimension(70, 20));
		jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SingleModeFrame.this.jButton_cancelActionPerformed(evt);
			}
		});

		jTextField_degree.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_degree.setText("3");
		jTextField_degree.setPreferredSize(new java.awt.Dimension(50, 21));

		jLabel_protocol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_protocol.setText("Protocol type:");

		jRadioButton_naive.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_naive.setSelected(true);
    jRadioButton_naive.setText("MultiSkipGraph protocol ");
		jRadioButton_naive.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SingleModeFrame.this.jRadioButton_naiveActionPerformed(evt);
			}
		});

		jRadioButton_alternative.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jRadioButton_alternative.setText("MultiSkipGraph* protocol");
		jRadioButton_alternative.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SingleModeFrame.this.jRadioButton_alternativeActionPerformed(evt);
			}
		});

		jTextField_avgDegree.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_avgDegree.setText("3");
		jTextField_avgDegree.setPreferredSize(new java.awt.Dimension(50, 21));

		jRadioButton_random.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_random.setText("Random graph");
		jRadioButton_random.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SingleModeFrame.this.jRadioButton_randomActionPerformed(evt);
			}
		});

		jRadioButton_both.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jRadioButton_both.setText("Both for comparision");
		jRadioButton_both.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SingleModeFrame.this.jRadioButton_bothActionPerformed(evt);
			}
		});

		jLabel_tests.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_tests.setText("Number of Tests:");

		jTextField_numOfTests.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jTextField_numOfTests.setText("1");
		jTextField_numOfTests.setPreferredSize(new java.awt.Dimension(50, 21));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
		this.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(36, 36, 36)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jRadioButton_both)
								.addComponent(jRadioButton_alternative).addComponent(jRadioButton_naive).addComponent(jLabel_protocol)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel_options)
												.addComponent(jCheckBox_saveData)
												.addComponent(jLabel_tests)
												.addGroup(
														layout.createSequentialGroup().addGap(37, 37, 37).addComponent(jButton_generate,
																javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGap(47, 47, 47).addComponent(jButton_cancel,
														javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup().addGap(100, 100, 100)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jCheckBox_makeFilm).addComponent(jTextField_numOfTests,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 62,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addComponent(jRadioButton_random).addComponent(jRadioButton_randomAvgDegree).addComponent(jRadioButton_scaleFree)
								.addComponent(jLabel_graphTypej)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel_search)
												.addComponent(jLabel_graphSize))
										.addGap(80, 80, 80)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jTextField_numOfNodes, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField_numOfSearches, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField_avgDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 62,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(43, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup()
				.addGap(42, 42, 42)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel_graphSize).addComponent(
						jTextField_numOfNodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jTextField_numOfSearches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel_search))
				.addGap(18, 18, 18).addComponent(jLabel_graphTypej).addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jRadioButton_scaleFree).addComponent(
						jTextField_degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(7, 7, 7)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jRadioButton_randomAvgDegree)
						.addComponent(jTextField_avgDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jRadioButton_random).addGap(18, 18, 18)
				.addComponent(jLabel_protocol).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jRadioButton_naive)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jRadioButton_alternative)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jRadioButton_both).addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel_tests).addComponent(
						jTextField_numOfTests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(19, 19, 19).addComponent(jLabel_options).addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jCheckBox_saveData)
						.addComponent(jCheckBox_makeFilm))
				.addGap(39, 39, 39)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jButton_generate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(51, Short.MAX_VALUE)));

		this.pack();
		this.setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jRadioButton_scaleFreeActionPerformed(java.awt.event.ActionEvent evt) {
		// GEN-FIRST:event_jRadioButton_scaleFreeActionPerformed
		if (this.jRadioButton_scaleFree.isSelected()) {
			this.jTextField_degree.setEnabled(true);
			this.jTextField_avgDegree.setEnabled(false);
			this.jRadioButton_randomAvgDegree.setSelected(false);
			this.jRadioButton_random.setSelected(false);
		} else {
			this.jTextField_degree.setEnabled(false);
			this.jTextField_avgDegree.setEnabled(true);
			this.jRadioButton_randomAvgDegree.setSelected(true);
			this.jRadioButton_random.setSelected(false);
		}
	}// GEN-LAST:event_jRadioButton_scaleFreeActionPerformed

	private void jRadioButton_randomAvgDegreeActionPerformed(java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_jRadioButton_randomAvgDegreeActionPerformed
		if (this.jRadioButton_randomAvgDegree.isSelected()) {
			this.jTextField_avgDegree.setEnabled(true);
			this.jTextField_degree.setEnabled(false);
			this.jRadioButton_random.setSelected(false);
			this.jRadioButton_scaleFree.setSelected(false);
		} else {
			this.jTextField_avgDegree.setEnabled(false);
			this.jTextField_degree.setEnabled(false);
			this.jRadioButton_random.setSelected(true);
			this.jRadioButton_scaleFree.setSelected(false);
		}
	}// GEN-LAST:event_jRadioButton_randomAvgDegreeActionPerformed

	private void jRadioButton_randomActionPerformed(java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_jRadioButton_randomActionPerformed
		if (this.jRadioButton_random.isSelected()) {
			this.jTextField_avgDegree.setEnabled(false);
			this.jTextField_degree.setEnabled(false);
			this.jRadioButton_randomAvgDegree.setSelected(false);
			this.jRadioButton_scaleFree.setSelected(false);
		} else {
			this.jTextField_avgDegree.setEnabled(false);
			this.jTextField_degree.setEnabled(true);
			this.jRadioButton_scaleFree.setSelected(true);
			this.jRadioButton_randomAvgDegree.setSelected(false);
		}
	}//GEN-LAST:event_jRadioButton_randomActionPerformed

	private void jRadioButton_naiveActionPerformed(java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_jRadioButton_naiveActionPerformed
		if (this.jRadioButton_naive.isSelected()) {
			this.jRadioButton_alternative.setSelected(false);
			this.jRadioButton_both.setSelected(false);
		} else {
			this.jRadioButton_alternative.setSelected(true);
			this.jRadioButton_both.setSelected(false);
		}
	}//GEN-LAST:event_jRadioButton_naiveActionPerformed

	private void jRadioButton_alternativeActionPerformed(java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_jRadioButton_alternativeActionPerformed
		if (this.jRadioButton_alternative.isSelected()) {
			this.jRadioButton_naive.setSelected(false);
			this.jRadioButton_both.setSelected(false);
		} else {
			this.jRadioButton_naive.setSelected(true);
			this.jRadioButton_both.setSelected(false);
		}
	}//GEN-LAST:event_jRadioButton_alternativeActionPerformed

	private void jRadioButton_bothActionPerformed(java.awt.event.ActionEvent evt) {
		//GEN-FIRST:event_jRadioButton_bothActionPerformed
		if (this.jRadioButton_both.isSelected()) {
			this.jRadioButton_naive.setSelected(false);
			this.jRadioButton_alternative.setSelected(false);
		} else {
			this.jRadioButton_naive.setSelected(true);
			this.jRadioButton_alternative.setSelected(false);
		}
	}//GEN-LAST:event_jRadioButton_bothActionPerformed

	private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {
		// GEN-FIRST:event_jButton_cancelActionPerformed
		this.setVisible(false);
		if (this.parent != null) {
			this.parent.setVisible(true);
		}
		this.dispose();
	}// GEN-LAST:event_jButton_cancelActionPerformed

	private void jButton_simulateActionPerformed(java.awt.event.ActionEvent evt) {
		// GEN-FIRST:event_jButton_generateActionPerformed
		this.setVisible(false);
		int numOfNodes = Integer.parseInt(this.jTextField_numOfNodes.getText());
		int numOfSearches = Integer.parseInt(this.jTextField_numOfSearches.getText());
		int numOfTests = Integer.parseInt(this.jTextField_numOfTests.getText());
		int degree = Integer.parseInt(this.jTextField_degree.getText());
		GraphType graphType = GraphType.ScaleFree;
		if (this.jRadioButton_randomAvgDegree.isSelected()) {
			degree = Integer.parseInt(this.jTextField_avgDegree.getText());
			graphType = GraphType.RandomAvgDegree;
		}
		if (this.jRadioButton_random.isSelected()) {
			graphType = GraphType.Random;
		}
		Protocol protocol = Protocol.Naive;
		if (this.jRadioButton_alternative.isSelected()) {
			protocol = Protocol.Alternative;
		}
		if (this.jRadioButton_both.isSelected()) {
			protocol = Protocol.Both;
		}
		boolean saveData = true;
		if (!this.jCheckBox_saveData.isSelected()) {
			saveData = false;
		}
		boolean makeFilm = false;
		if (this.jCheckBox_makeFilm.isSelected()) {
			makeFilm = true;
		}
		MsController.getInstance().setProperties(protocol, numOfNodes, numOfSearches, graphType, degree, numOfTests, saveData, makeFilm);
		MsController.getInstance().simulateSingle(protocol, this);
	}// GEN-LAST:event_jButton_generateActionPerformed

}
